### ISSUE TITLE
CMake build script

### ISSUE THREAD

**Issue by ghost** [copperspice/cs_signal#3]
Can you provide a CMake build script for building cs_signal? I tried building them with autotool and it did succeed but I couldn't find any generated lib to link against. The only output files I got were the following -

bin/libCsSignal-0.dll
lib/licCsSignal.dll.a // This looks like the library but has the wrong extension?
lib/libCsSignal.la

Also, install should have created a "include" directory with necessary public headers which was also missing. The included autoconf doesn't have an option to build debug and release configurations.

Optionally, additional instructions/documentation on how to build these libraries for different platforms would help.

**Comment by agserm** [comment]
We have it on our road map to generate CMake files for the cs_signal library. Did you attempt to use the autotools build with MSVC? The autotools build only works for a MinGW toolchain.

We have just pushed a commit to resolve the header installation process and to update the name of the DLL removing the `-0` suffix. The correct file to use is libCsSignal.dll, which will be installed to the bin directory.

**Comment by de1001** [comment]
I built it successfully after a few attempts. Documentation was little to no help on this adventure. I would still push for platform specific build tools.

I will check out the latest push soon. I would rather not change my environment in middle of a sprint.

**Comment by agserm** [comment]
We do have documentation on how to build with autotools. In our copperspice overview documentation, we document how to build a sample project called HelloLunch, as well as how to build the KitchenSink demo application. We have it noted to add this same information to the cs_signal documentation.

You mention "platform specific build tools." Can you tell us what you are referring to? We updated the autotools build yesterday, and we will be adding CMake.

Other than the two issues we resolved in the autotools build system, what problems did you encounter? What can we do to streamline the build process?

**Comment by de1001** [comment]
I integrated latest changes today and noticed that the dll are now named with correct extension however, the import libs are still wrong. They are currently named libCsSignal.dll.a and libCsSignal.la

**Comment by bgeller** [comment]
I am not sure if I read your prior comments accurately. If you are asking for different build files for every platform, this would be a CI headache. Also, trying to set up different build files for each platform is not viable for cross platform development. We do absolutely agree that proper CMake files are needed for CsSignal and they are being tested.

It is not practical to restrict the version of MinGW as others may in fact be fine but not ones we tested. We simply document a known working version which matches the Windows binary files we distribute.

**Comment by agserm** [comment]
> I integrated latest changes today and noticed that the dll are now named with correct extension however, the import libs are still wrong. They are currently named libCsSignal.dll.a and libCsSignal.la

I am not sure what issue you are reporting here. Those are the correct names for the MinGW ABI libtool library files. Can you tell us what filenames you expected to see?

**Comment by de1001** [comment]
> 
> 
> > I integrated latest changes today and noticed that the dll are now named with correct extension however, the import libs are still wrong. They are currently named libCsSignal.dll.a and libCsSignal.la
> 
> I am not sure what issue you are reporting here. Those are the correct names for the MinGW ABI libtool library files. Can you tell us what filenames you expected to see?

I was expecting a ".lib" file for use with VS.

I have never worked with MinGW so my expectation might be off here. Our project uses VS build tool and the intention was that cs_signal can be built with its own build tool and generated outputs can be consumed directly in our project as prebuilt artifacts.

**Comment by de1001** [comment]
> I am not sure if I read your prior comments accurately. If you are asking for different build files for every platform, this would be a CI headache. Also, trying to set up different build files for each platform is not viable for cross platform development. We do absolutely agree that proper CMake files are needed for CsSignal and they are being tested.
> 
> It is not practical to restrict the version of MinGW as others may in fact be fine but not ones we tested. We simply document a known working version which matches the Windows binary files we distribute.

No that wasn't the expectation. If you provide CMake files, CMake has option that can generate VS, xcode, and other environment specific projects.

**Comment by agserm** [comment]
This has been resolved by 856751e which provides full CMake build files.
